validations for iris_pgsql.dcs_iris:
  # Numeric Metrics
  - sepal length min size:
      on: min(sepal_length)
      threshold: "= 0"
  - sepal length max size:
      on: max(sepal_length)
      threshold: "= 150"
  - sepal length avg size:
      on: avg(sepal_length)
      threshold: "> 0 & < 1000"
  - sepal length sum size:
      on: sum(sepal_length)
      threshold: "> 0 & < 1000"
  - sepal length variance size:
      on: variance(sepal_length)
      threshold: "< 1"
  - sepal length stddev size:
      on: stddev(sepal_length)
      threshold: "< 0.5"
  # Percentile Validations
  - sepal length 20th percentile:
      on: percentile_20(sepal_length)
      threshold: "> 10"

  - sepal length 40th percentile:
      on: percentile_40(sepal_length)
      threshold: "> 20"

  - sepal length 60th percentile:
      on: percentile_60(sepal_length)
      threshold: "> 30"

  - sepal length 80th percentile:
      on: percentile_80(sepal_length)
      threshold: "> 40"

  - sepal length 90th percentile:
      on: percentile_90(sepal_length)
      threshold: "> 50"

    # Zero Numeric Validations
  - sepal length zero count:
      on: count_zero(sepal_length)
      threshold: "< 5"
  - sepal length zero percent:
      on: percent_zero(sepal_length)
      threshold: "< 10"


  # **Negative Value Validations**
  - price negative value count:
      on: count_negative(price)
      threshold: "< 2"

  - price negative value percentage:
      on: percent_negative(price)
      threshold: "< 40"

  # Uniqueness Metrics
  - species duplicate count:
      on: count_duplicate(species)
      threshold: "< 100"
  - species distinct count:
      on: count_distinct(species)
      threshold: "> 0"

  # Completeness Metrics
  - sepal length null count:
      on: count_null(sepal_length)
      threshold: "= 0"
  - sepal length null percentage:
      on: percent_null(sepal_length)
      threshold: "= 0"
  - species empty string count:
      on: count_empty_string(species)
      threshold: "= 0"
  - species empty string percentage:
      on: percent_empty_string(species)
      threshold: "= 0"

  # Custom Metrics
  - sepal length custom sql example:
      on: custom_sql
      query: "SELECT avg(sepal_length) * 2 FROM dcs_iris"
      threshold: "> 0 & < 10"

  # Reliability Metrics
  - dcs_iris rows count:
      on: count_rows
      threshold: "> 0"
  - dcs_iris last update count:
      on: freshness(timestamp)
      threshold: "> 0"

  # Filtered Metrics
  - dcs_iris rows count with filter:
      on: count_rows
      threshold: "< 50"
      where: "species = 'virginica'"
  - dcs_iris min with filter:
      on: min(sepal_length)
      threshold: "= 4"
      where: "species = 'virginica'"

  # Validity Validations
  - dcs_iris invalid values count species:
      on: count_invalid_values(species)
      values: ["versicolor"]
      threshold: "< 10"

  - dcs_iris invalid values percent species:
      on: percent_invalid_values(species)
      values: ["virginica"]

  - dcs_iris valid values count species:
      on: count_valid_values(species)
      values: ["virginica", "setosa"]

  - dcs_iris valid values percent species:
      on: percent_valid_values(species)
      values: ["setosa"]

  - dcs_iris count invalid regex species:
      on: count_invalid_regex(species)
      regex: ".e.*"

  - dcs_iris count invalid regex percent species:
      on: percent_invalid_regex(species)
      regex: ".e.*"

  - dcs_iris count valid regex species:
      on: count_valid_regex(species)
      regex: "^(setosa|virginica)$"

  - dcs_iris count valid regex percent species:
      on: percent_valid_regex(species)
      regex: "^(setosa|virginica)$"

  # delta validation
  - reference count difference count rows:
      on: delta count_rows
      threshold: < 10
      ref: iris_pgsql.dcs_diamond